steps:
  - name: test
    when:
      event: [tag, push]
    image: maven:3-jdk-11
    commands:
      - mvn -B -DskipTests clean package
    volumes:
      - /home/docker/woodpecker/files/m2:/root/.m2

  - name: archive-artifact
    when:
      event: [tag, push]
    image: alpine:latest
    commands:
      - mkdir -p /builds/innaircbot
      - cp target/InnaIrcBot-*jar /builds/innaircbot/
    volumes:
      - /home/www/builds:/builds
